# 1.Tạo array 1D kích thước 3x3 với giá trị True

In [9]:
import numpy as np
arr = np.array([[True, True, True],
                [True, True, True],
                [True, True, True]])
print("Array có kích thước 3x3:\n", arr)

Array có kích thước 3x3:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


# 2.Tạo array 1D từ [0, 1, 2, 3, 4, 5, 6, 7, 8], đổi sang array 2 chiều 3x3

In [11]:
arr_1D = np.array([0,1,2,3,4,5,6,7,8])
arr_2D = arr_1D.reshape(3, 3)
print("arr_2D:\n", arr_2D)


arr_2D:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


# 3.Đảo ngược các dòng và cột của arr_2D

In [7]:
arr_2D = np.flip(arr_1D, axis=0)
arr_2D = np.flip(arr_2D, axis=1)
print("Array sau khi đảo ngược:\n", arr_2D)

Array sau khi đảo ngược:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


# 4.Đảo ngược các dòng của arr_2D

In [12]:
arr_2D = arr_2D[::-1]
print("arr_2D:\n", arr_2D)

arr_2D:
 [[6 7 8]
 [3 4 5]
 [0 1 2]]


# 5.Đảo ngược các cột của arr_2D

In [13]:
arr_2D = arr_2D[:, ::-1]
print("arr_2D:\n", arr_2D)

arr_2D:
 [[8 7 6]
 [5 4 3]
 [2 1 0]]


# 6.Tạo arr_2D_null và kiểm tra giá trị rỗng

In [15]:
arr_2D_null = np.array([[1, 2, 3],[np.nan, 5, 6],[7, np.nan, 9],[4, 5, 6]])
print("arr_2D_null:\n", arr_2D_null)
null_check = np.isnan(arr_2D_null)
print("Check for NaN values:\n", null_check)

arr_2D_null:
 [[ 1.  2.  3.]
 [nan  5.  6.]
 [ 7. nan  9.]
 [ 4.  5.  6.]]
Check for NaN values:
 [[False False False]
 [ True False False]
 [False  True False]
 [False False False]]


# 7.Thay thế các giá trị null bằng 0

In [16]:
arr_2D_null[np.isnan(arr_2D_null)] = 0
print("arr_2D_null:\n", arr_2D_null)

arr_2D_null:
 [[1. 2. 3.]
 [0. 5. 6.]
 [7. 0. 9.]
 [4. 5. 6.]]
