- 1.Đọc dữ liệu từ file CSV

In [1]:
import numpy as np 
import csv
file_path = 'C:/17A1DHKL/LAB2/DATA/diem_hoc_phan.csv'
data = []
with open(file_path, newline='', encoding='utf-8')as csvfile:
    reader = csv.reader(csvfile)
    next(reader) #bỏ qua tiêu đề cột
    for row in reader:
        data.append([float(score) for score in row[2:]])
        #lặp trong các hàng lấy từ cột 2 trở đi
# Chuyển đổi dữ liệu điểm thành mảng NumPy
diem_hp = np.array(data, dtype=float)
print("Dữ liệu điểm số dưới dạng mảng NumPy:\n",diem_hp)


Dữ liệu điểm số dưới dạng mảng NumPy:
 [[3.04 3.39 6.7 ]
 [5.8  6.41 6.62]
 [2.59 3.57 9.16]
 [3.81 8.78 9.24]
 [8.91 9.64 6.39]
 [3.23 4.72 6.17]
 [2.35 3.29 6.89]
 [2.48 3.81 4.84]
 [3.23 2.61 4.52]
 [7.02 9.01 9.15]
 [2.29 4.48 5.51]
 [3.51 7.19 5.13]
 [6.74 7.78 6.19]
 [9.86 4.64 3.33]
 [8.04 5.12 4.77]
 [2.74 8.88 5.8 ]
 [3.04 6.88 3.91]
 [5.87 4.41 8.84]
 [8.46 2.63 4.91]
 [3.74 6.71 3.44]
 [5.67 8.05 6.03]
 [8.12 2.46 3.87]
 [9.4  5.31 5.13]
 [3.91 5.09 8.82]
 [4.26 5.78 8.14]
 [4.41 2.66 5.4 ]
 [3.23 8.3  8.64]
 [9.25 8.29 9.1 ]
 [6.08 2.67 6.39]
 [3.85 7.71 5.75]]


2. Quy đổi từ thang điểm 10 sang điểm tín chỉ

In [2]:
def quy_doi_diem(diem):
    if diem >= 8.5:
        return 'A'
    elif diem >= 8.0:
        return 'B+'
    elif diem >= 7.0:
        return 'B'
    elif diem >= 6.5:
        return 'C+'
    elif diem >= 5.5:
        return 'C'
    elif diem >= 5.0:
        return 'D+'
    elif diem >= 4.0:
        return 'D'
    else:
        return 'F'
# Áp dụng qui đổi cho tất cả điểm trong mảng diem_hp
diem_tinchi = np.vectorize(quy_doi_diem)(diem_hp)
print("Điểm tín chỉ cho các học phần:\n",diem_tinchi)

Điểm tín chỉ cho các học phần:
 [['F' 'F' 'C+']
 ['C' 'C' 'C+']
 ['F' 'F' 'A']
 ['F' 'A' 'A']
 ['A' 'A' 'C']
 ['F' 'D' 'C']
 ['F' 'F' 'C+']
 ['F' 'F' 'D']
 ['F' 'F' 'D']
 ['B' 'A' 'A']
 ['F' 'D' 'C']
 ['F' 'B' 'D+']
 ['C+' 'B' 'C']
 ['A' 'D' 'F']
 ['B+' 'D+' 'D']
 ['F' 'A' 'C']
 ['F' 'C+' 'F']
 ['C' 'D' 'A']
 ['B+' 'F' 'D']
 ['F' 'C+' 'F']
 ['C' 'B+' 'C']
 ['B+' 'F' 'F']
 ['A' 'D+' 'D+']
 ['F' 'D+' 'A']
 ['D' 'C' 'B+']
 ['D' 'F' 'D+']
 ['F' 'B+' 'A']
 ['A' 'B+' 'A']
 ['C' 'F' 'C']
 ['F' 'B' 'C']]


3. Chia tách dữ liệu theo từng học phần

In [3]:
hp1 = diem_hp[:, 0]  # Điểm HP1
hp2 = diem_hp[:, 1]  
hp3 = diem_hp[:, 2]  
print("\nĐiểm học phần 1:", hp1)
print("Điểm học phần 2:", hp2)
print("Điểm học phần 3:", hp3)


Điểm học phần 1: [3.04 5.8  2.59 3.81 8.91 3.23 2.35 2.48 3.23 7.02 2.29 3.51 6.74 9.86
 8.04 2.74 3.04 5.87 8.46 3.74 5.67 8.12 9.4  3.91 4.26 4.41 3.23 9.25
 6.08 3.85]
Điểm học phần 2: [3.39 6.41 3.57 8.78 9.64 4.72 3.29 3.81 2.61 9.01 4.48 7.19 7.78 4.64
 5.12 8.88 6.88 4.41 2.63 6.71 8.05 2.46 5.31 5.09 5.78 2.66 8.3  8.29
 2.67 7.71]
Điểm học phần 3: [6.7  6.62 9.16 9.24 6.39 6.17 6.89 4.84 4.52 9.15 5.51 5.13 6.19 3.33
 4.77 5.8  3.91 8.84 4.91 3.44 6.03 3.87 5.13 8.82 8.14 5.4  8.64 9.1
 6.39 5.75]


4. Phân tích dữ liệu theo từng học phần

In [6]:
# Phân tích tổng, trung bình và độ lệch chuẩn cho từng học phần
tongs_hp1 = np.sum(hp1)
tongs_hp2 = np.sum(hp2)
tongs_hp3 = np.sum(hp3)

avg_hp1 = np.mean(hp1)
avg_hp2 = np.mean(hp2)
avg_hp3 = np.mean(hp3)

std_hp1 = np.std(hp1)
std_hp2 = np.std(hp2)
std_hp3 = np.std(hp3)
print(f"\nTổng điểm học phần 1: {tongs_hp1}, Trung bình: {avg_hp1}, Độ lệch chuẩn: {std_hp1}")
print(f"Tổng điểm học phần 2: {tongs_hp2}, Trung bình: {avg_hp2}, Độ lệch chuẩn: {std_hp2}")
print(f"Tổng điểm học phần 3: {tongs_hp3}, Trung bình: {avg_hp3}, Độ lệch chuẩn: {std_hp3}")


Tổng điểm học phần 1: 154.92999999999998, Trung bình: 5.1643333333333326, Độ lệch chuẩn: 2.4078519934211533
Tổng điểm học phần 2: 170.27, Trung bình: 5.675666666666667, Độ lệch chuẩn: 2.2494765070023637
Tổng điểm học phần 3: 188.78, Trung bình: 6.292666666666666, Độ lệch chuẩn: 1.8082292135923723


5. Phân tích điểm tổng hợp

In [5]:
from collections import Counter

# Chuyển đổi các điểm tín chỉ thành mảng 1 chiều
flat_diem_tinchi = diem_tinchi.flatten()
# Tính số lượng sinh viên đạt mỗi loại điểm chữ trên tổng số học phần
counter = Counter(flat_diem_tinchi)
print("Số lượng sinh viên đạt mỗi loại điểm chữ trên tổng số học phần:")
for grade, count in counter.items():
    print(f"{grade}: {count}")

Số lượng sinh viên đạt mỗi loại điểm chữ:
F: 28
C+: 6
C: 14
A: 15
D: 10
B: 4
D+: 6
B+: 7
